# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_receipt_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_image',
            field=models.ImageField(default='static/uploads/no-img.jpg', upload_to='uploads/'),
        ),
    ]
