# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20171024_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
