# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20171026_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='name',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='uuid',
        ),
    ]
